name: eventide_example
description: "Demonstrates how to use the eventide plugin."
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  eventide:
    path: ../
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  value_state:
    git:
      url: https://github.com/zemanux/value_state.git
      ref: refacto
      path: packages/value_state
  timezone: ^0.10.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true